version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9

    working_directory: ~/client

    steps:
      - checkout:
          path: ~/client

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "client/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: cd client && npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "client/package.json" }}

      # run tests!
      - run: cd client && npm run test:unit
      - run: cd client && npm run test:e2e